import 'package:clock/clock.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart';
import 'package:splitwiththemachine/main.dart';
import 'package:integration_test/integration_test.dart';
import 'package:mockito/annotations.dart';

import 'package:splitwiththemachine/data/repositories.dart';
import 'package:splitwiththemachine/data/services.dart';

import 'mock_setup.dart';

// Only way to generate mocks with null safety!
@GenerateMocks(<Type>[SplitWithMeService])
import 'app_test.mocks.dart'; // File generated by build_runner

void main() {
  // Force English (US) locale before all tests
  Intl.defaultLocale = 'en_US';

  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final mockService = buildMockService();

  group('end-to-end test', () {
    testWidgets('load the initial expense data', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));
      expect(find.text("Groceries"), findsOneWidget);
      expect(find.text("Coffee"), findsOneWidget);
      expect(find.text("Bus Ticket"), findsOneWidget);
      expect(find.text("Dinner"), findsOneWidget);
      expect(find.text("Books"), findsOneWidget);
      expect(find.text("Gym Membership"), findsOneWidget);
      expect(find.text("Balance: \$ 0.00"), findsExactly(5));
      expect(find.text("Balance: \$ 3.30"), findsOne);
    });

    testWidgets('load details of a expense (no friends added)', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-2"));
      final inkWell = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWell);

      await tester.pumpAndSettle();

      // Expense detail
      expect(find.text("Coffee"), findsExactly(2));
      expect(find.text("\$ 3.10"), findsOne);
      expect(find.text("\$ 0.00"), findsOne);
      expect(find.text("Saturday, January 4, 2025"), findsOne);

      // Friends on expense, nothing
      expect(find.text("No friends added"), findsOne);
    });

    testWidgets('load details of a expense (with friends added)', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWell = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWell);

      await tester.pumpAndSettle();

      // Expense detail
      expect(find.text("Books"), findsExactly(2));
      expect(find.text("\$ 120.60"), findsOne);
      expect(find.text("\$ 3.30"), findsOne);
      expect(find.text("Saturday, March 2, 2024"), findsOne);

      // Friends on expense
      expect(find.byType(CircleAvatar), findsExactly(3));
      expect(find.text("Nerea"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOneWidget);
      expect(find.text("Alex"), findsOne);
      expect(find.textContaining("Credit: \$ 1.30"), findsOne);
      expect(find.text("Dani"), findsOne);
      expect(find.textContaining("Credit: \$ 2.00"), findsOne);
      expect(find.textContaining("Debit: \$ 40.20"), findsExactly(3));
    });

    testWidgets('add an expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Add expense button
      final addExpenseFab = find.byTooltip("Add an expense");
      await tester.tap(addExpenseFab);
      await tester.pumpAndSettle();

      // Change date
      await tester.tap(find.byIcon(Icons.calendar_today));
      await tester.pumpAndSettle();

      for (var i = 0; i < 2; i++) { // Go back 2 months
        await tester.tap(find.byIcon(Icons.chevron_left));
        await tester.pumpAndSettle();
      }

      await tester.tap(find.text("15")); // Select 15th day
      await tester.pumpAndSettle();
      await tester.tap(find.text("Confirm Date"));
      await tester.pumpAndSettle();

      // Find fields
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

      // Verify fields
      expect(descriptionFieldFinder, findsOneWidget);
      expect(amountFieldFinder, findsOneWidget);

      // Fill fields
      await tester.enterText(descriptionFieldFinder, "New TV");
      await tester.enterText(amountFieldFinder, "1500.99");
      await tester.pumpAndSettle();

      // Save expense
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Expense 'New TV' added"), findsOne);
      await tester.pump(const Duration(seconds: 3));

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(7));
      expect(find.text("New TV"), findsOne);
    });

    testWidgets('add an expense with error', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Add expense button
      final addExpenseFab = find.byTooltip("Add an expense");
      await tester.tap(addExpenseFab);
      await tester.pumpAndSettle();

      // Save with description and amount fields empty
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with amount field empty
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      await tester.enterText(descriptionFieldFinder, "New TV");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with description field empty
      await tester.enterText(descriptionFieldFinder, ''); // Clear description
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');
      await tester.enterText(amountFieldFinder, "1500.99");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);
    });

    testWidgets('add a duplicated expense', (
        tester,
        ) async {

      // Set a date to always be in November
      final fakeNow = DateTime(2025, 11, 21);

      await withClock(Clock.fixed(fakeNow), () async{
        await tester.pumpWidget(MyApp(
          expenseRepository: ExpenseRepository(service: mockService),
          friendRepository: FriendRepository(service: mockService),
        ));

        await tester.pumpAndSettle();

        // Add expense button
        final addExpenseFab = find.byTooltip("Add an expense");
        await tester.tap(addExpenseFab);
        await tester.pumpAndSettle();

        // Fill fields
        final descriptionFieldFinder = find.widgetWithText(
            TextField, 'Description');
        final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

        // Add same expense
        await tester.enterText(descriptionFieldFinder, "Gym Membership");
        await tester.enterText(amountFieldFinder, "47.50");
        await tester.pumpAndSettle();

        // Change date
        await tester.tap(find.byIcon(Icons.calendar_today));
        await tester.pumpAndSettle();

        for (var i = 0; i < 10; i++) {
          await tester.tap(find.byIcon(Icons.chevron_left));
          await tester.pumpAndSettle();
        }

        await tester.tap(find.text("12"));
        await tester.pumpAndSettle();
        await tester.tap(find.text("Confirm Date"));
        await tester.pumpAndSettle();

        // Save expense
        final saveExpenseFab = find.byTooltip("Save");
        await tester.tap(saveExpenseFab);
        await tester.pumpAndSettle();

        // Duplicated expense error (SnackBar)
        final errorMessageFinder = find.text("Expense 'Gym Membership' is "
            "already added");
        expect(errorMessageFinder, findsOneWidget);

        final errorSnackBarFinder = find.ancestor(
            of: errorMessageFinder,
            matching: find.byType(Material)
        );
        expect(errorSnackBarFinder, findsOneWidget);

        final dismissButton = find.text("DISMISS");
        expect(dismissButton, findsOneWidget);
        await tester.tap(dismissButton);
        await tester.pumpAndSettle();  

        expect(errorSnackBarFinder, findsNothing); // Verify SnackBar is gone
      });
    });

    testWidgets('add friend to expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-2"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);

      await tester.pumpAndSettle();

      final addFriendFab = find.byTooltip("Add friend");
      await tester.tap(addFriendFab);
      await tester.pumpAndSettle();

      expect(find.byType(CircleAvatar), findsExactly(6));
      expect(find.text("Nerea"), findsOneWidget);
      expect(find.text("Pepe"), findsOneWidget);
      expect(find.text("Dani"), findsOneWidget);
      expect(find.text("Alex"), findsOneWidget);
      expect(find.text("Marcos"), findsOneWidget);
      expect(find.text("Manolo"), findsOneWidget);

      final friendRow = find.byKey(ValueKey("friend-5"));
      final inkWellFriend = find.descendant(
          of: friendRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellFriend);
      await tester.pumpAndSettle();

      expect(find.text("'Marcos' added to 'Coffee'"), findsOne);
      expect(find.text("Marcos"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOne);
      expect(find.textContaining("Debit: \$ 1.55"), findsOne);
    });

    testWidgets('edit expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      final editExpenseFab = find.byTooltip("Edit expense");
      await tester.tap(editExpenseFab);
      await tester.pumpAndSettle();

      // Find fields
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

      // Verify fields
      expect(descriptionFieldFinder, findsOneWidget);
      expect(amountFieldFinder, findsOneWidget);

      // Fill fields
      await tester.enterText(descriptionFieldFinder, "Travel to Singapore");
      await tester.enterText(amountFieldFinder, "1700.4");
      await tester.pumpAndSettle();

      // Change date
      await tester.tap(find.byIcon(Icons.calendar_today));
      await tester.pumpAndSettle();

      for (var i = 0; i < 3; i++) { // Go forward 2 months
        await tester.tap(find.byIcon(Icons.chevron_right));
        await tester.pumpAndSettle();
      }

      await tester.tap(find.text("15")); // Select 15th day
      await tester.pumpAndSettle();
      await tester.tap(find.text("Confirm Date"));
      await tester.pumpAndSettle();

      // Save button
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Expense 'Travel to Singapore' edited"), findsOne);

      expect(find.text("Nerea"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOne);
      expect(find.textContaining("Debit: \$ 566.8"), findsOne);

      // Go back
      final goBack = find.byIcon(Icons.arrow_back);
      await tester.tap(goBack);
      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));
    });
  });
}