import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:splitwiththemachine/main.dart';
import 'package:integration_test/integration_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';

import 'package:splitwiththemachine/data/repositories.dart';
import 'package:splitwiththemachine/data/services.dart';
import 'package:splitwiththemachine/data/models.dart';

import 'mock_setup.dart';

// Only way to generate mocks with null safety!
@GenerateMocks(<Type>[SplitWithMeService])
import 'app_test.mocks.dart'; // File generated by build_runner

void main() {

  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final mockService = buildMockService();


}