import 'package:clock/clock.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart';
import 'package:splitwiththemachine/main.dart';
import 'package:integration_test/integration_test.dart';
import 'package:mockito/annotations.dart';

import 'package:splitwiththemachine/data/repositories.dart';
import 'package:splitwiththemachine/data/services.dart';

import 'mock_setup.dart';

// Only way to generate mocks with null safety!
@GenerateMocks(<Type>[SplitWithMeService])
import 'app_test.mocks.dart'; // File generated by build_runner

void main() {
  // Force English (US) locale before all tests
  Intl.defaultLocale = 'en_US';

  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final mockService = buildMockService();

  group('end-to-end test', () {
    testWidgets('load the initial expense data', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));
      expect(find.text("Groceries"), findsOneWidget);
      expect(find.text("Coffee"), findsOneWidget);
      expect(find.text("Bus Ticket"), findsOneWidget);
      expect(find.text("Dinner"), findsOneWidget);
      expect(find.text("Books"), findsOneWidget);
      expect(find.text("Gym Membership"), findsOneWidget);
      expect(find.text("Balance: \$ 0.00"), findsExactly(5));
      expect(find.text("Balance: \$ 3.30"), findsOne);
    });

    testWidgets('load details of a expense (no friends added)', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-2"));
      final inkWell = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWell);

      await tester.pumpAndSettle();

      // Expense detail
      expect(find.text("Coffee"), findsExactly(2));
      expect(find.text("\$ 3.10"), findsOne);
      expect(find.text("\$ 0.00"), findsOne);
      expect(find.text("Saturday, January 4, 2025"), findsOne);

      // Friends on expense, nothing
      expect(find.text("No friends added"), findsOne);
    });

    testWidgets('load details of a expense (with friends added)', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWell = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWell);

      await tester.pumpAndSettle();

      // Expense detail
      expect(find.text("Books"), findsExactly(2));
      expect(find.text("\$ 120.60"), findsOne);
      expect(find.text("\$ 3.30"), findsOne);
      expect(find.text("Saturday, March 2, 2024"), findsOne);

      // Friends on expense
      expect(find.byType(CircleAvatar), findsExactly(3));
      expect(find.text("Nerea"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOneWidget);
      expect(find.text("Alex"), findsOne);
      expect(find.textContaining("Credit: \$ 1.30"), findsOne);
      expect(find.text("Dani"), findsOne);
      expect(find.textContaining("Credit: \$ 2.00"), findsOne);
      expect(find.textContaining("Debit: \$ 40.20"), findsExactly(3));
    });

    testWidgets('add an expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Add expense button
      final addExpenseFab = find.byTooltip("Add an expense");
      await tester.tap(addExpenseFab);
      await tester.pumpAndSettle();

      // Change date
      await tester.tap(find.byIcon(Icons.calendar_today));
      await tester.pumpAndSettle();

      for (var i = 0; i < 2; i++) { // Go back 2 months
        await tester.tap(find.byIcon(Icons.chevron_left));
        await tester.pumpAndSettle();
      }

      await tester.tap(find.text("15")); // Select 15th day
      await tester.pumpAndSettle();
      await tester.tap(find.text("Confirm Date"));
      await tester.pumpAndSettle();

      // Find fields
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

      // Verify fields
      expect(descriptionFieldFinder, findsOneWidget);
      expect(amountFieldFinder, findsOneWidget);

      // Fill fields
      await tester.enterText(descriptionFieldFinder, "New TV");
      await tester.enterText(amountFieldFinder, "1500.99");
      await tester.pumpAndSettle();

      // Save expense
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Expense 'New TV' added"), findsOne);
      await tester.pump(const Duration(seconds: 3));

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(7));
      expect(find.text("New TV"), findsOne);
    });

    testWidgets('add an expense with error', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Add expense button
      final addExpenseFab = find.byTooltip("Add an expense");
      await tester.tap(addExpenseFab);
      await tester.pumpAndSettle();

      // Save with description and amount fields empty
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with amount field empty
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      await tester.enterText(descriptionFieldFinder, "New TV");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with description field empty
      await tester.enterText(descriptionFieldFinder, ''); // Clear description
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');
      await tester.enterText(amountFieldFinder, "1500.99");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);
    });

    testWidgets('add a duplicated expense', (
        tester,
        ) async {

      // Set a date to always be in November
      final fakeNow = DateTime(2025, 11, 21);

      await withClock(Clock.fixed(fakeNow), () async{
        await tester.pumpWidget(MyApp(
          expenseRepository: ExpenseRepository(service: mockService),
          friendRepository: FriendRepository(service: mockService),
        ));

        await tester.pumpAndSettle();

        // Add expense button
        final addExpenseFab = find.byTooltip("Add an expense");
        await tester.tap(addExpenseFab);
        await tester.pumpAndSettle();

        // Fill fields
        final descriptionFieldFinder = find.widgetWithText(
            TextField, 'Description');
        final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

        // Add same expense
        await tester.enterText(descriptionFieldFinder, "Gym Membership");
        await tester.enterText(amountFieldFinder, "47.50");
        await tester.pumpAndSettle();

        // Change date
        await tester.tap(find.byIcon(Icons.calendar_today));
        await tester.pumpAndSettle();

        for (var i = 0; i < 10; i++) {
          await tester.tap(find.byIcon(Icons.chevron_left));
          await tester.pumpAndSettle();
        }

        await tester.tap(find.text("12"));
        await tester.pumpAndSettle();
        await tester.tap(find.text("Confirm Date"));
        await tester.pumpAndSettle();

        // Save expense
        final saveExpenseFab = find.byTooltip("Save");
        await tester.tap(saveExpenseFab);
        await tester.pumpAndSettle();

        // Duplicated expense error (SnackBar)
        final errorMessageFinder = find.text("Expense 'Gym Membership' is "
            "already added");
        expect(errorMessageFinder, findsOneWidget);

        final errorSnackBarFinder = find.ancestor(
            of: errorMessageFinder,
            matching: find.byType(Material)
        );
        expect(errorSnackBarFinder, findsOneWidget);

        final dismissButton = find.text("DISMISS");
        expect(dismissButton, findsOneWidget);
        await tester.tap(dismissButton);
        await tester.pumpAndSettle();  

        expect(errorSnackBarFinder, findsNothing); // Verify SnackBar is gone
      });
    });

    testWidgets('add friend to expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      final expenseRow = find.byKey(ValueKey("expense-2"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);

      await tester.pumpAndSettle();

      final addFriendFab = find.byTooltip("Add friend");
      await tester.tap(addFriendFab);
      await tester.pumpAndSettle();

      expect(find.byType(CircleAvatar), findsExactly(6));
      expect(find.text("Nerea"), findsOneWidget);
      expect(find.text("Pepe"), findsOneWidget);
      expect(find.text("Dani"), findsOneWidget);
      expect(find.text("Alex"), findsOneWidget);
      expect(find.text("Marcos"), findsOneWidget);
      expect(find.text("Manolo"), findsOneWidget);

      final friendRow = find.byKey(ValueKey("friend-5"));
      final inkWellFriend = find.descendant(
          of: friendRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellFriend);
      await tester.pumpAndSettle();

      expect(find.text("'Marcos' added to 'Coffee'"), findsOne);
      expect(find.text("Marcos"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOne);
      expect(find.textContaining("Debit: \$ 1.55"), findsOne);
    });

    testWidgets('edit expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      final editExpenseFab = find.byTooltip("Edit expense");
      await tester.tap(editExpenseFab);
      await tester.pumpAndSettle();

      // Find fields
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

      // Verify fields
      expect(descriptionFieldFinder, findsOneWidget);
      expect(amountFieldFinder, findsOneWidget);

      // Fill fields
      await tester.enterText(descriptionFieldFinder, "Travel to Singapore");
      await tester.enterText(amountFieldFinder, "1700.4");
      await tester.pumpAndSettle();

      // Change date
      await tester.tap(find.byIcon(Icons.calendar_today));
      await tester.pumpAndSettle();

      for (var i = 0; i < 3; i++) { // Go forward 2 months
        await tester.tap(find.byIcon(Icons.chevron_right));
        await tester.pumpAndSettle();
      }

      await tester.tap(find.text("15")); // Select 15th day
      await tester.pumpAndSettle();
      await tester.tap(find.text("Confirm Date"));
      await tester.pumpAndSettle();

      // Save button
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Expense 'Travel to Singapore' edited"), findsOne);

      expect(find.text("Nerea"), findsOne);
      expect(find.textContaining("Credit: \$ 0.00"), findsOne);
      expect(find.textContaining("Debit: \$ 566.8"), findsOne);

      // Go back
      final goBack = find.byIcon(Icons.arrow_back);
      await tester.tap(goBack);
      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));
    });

    testWidgets('edit an expense with error', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      // Click on expense
      final editExpenseFab = find.byTooltip("Edit expense");
      await tester.tap(editExpenseFab);
      await tester.pumpAndSettle();

      // Find fields
      final descriptionFieldFinder = find.widgetWithText(TextField, 'Description');
      final amountFieldFinder = find.widgetWithText(TextField, 'Amount (\$)');

      // Verify fields
      expect(descriptionFieldFinder, findsOneWidget);
      expect(amountFieldFinder, findsOneWidget);

      // Save with description and amount fields empty
      await tester.enterText(descriptionFieldFinder, "");
      await tester.enterText(amountFieldFinder, "");
      final saveExpenseFab = find.byTooltip("Save");
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with amount field empty
      await tester.enterText(descriptionFieldFinder, "New TV");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);

      // Save with description field empty
      await tester.enterText(descriptionFieldFinder, ''); // Clear description
      await tester.enterText(amountFieldFinder, "1500.99");

      await tester.pumpAndSettle();
      await tester.tap(saveExpenseFab);
      await tester.pumpAndSettle();

      expect(find.text('Please fill in all fields correctly.'), findsOne);
    });

    testWidgets('delete friend from expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      final friendCard = find.byKey(ValueKey("friend-1"));
      await tester.drag(friendCard, const Offset(-500, 0)); // Slide to left
      await tester.pumpAndSettle();
      //await tester.pump(const Duration(seconds: 5));
      expect(find.text("Are you sure you want to delete Nerea from this expense?"), findsOne);
      final deleteButton = find.text("Delete");
      await tester.tap(deleteButton);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("'Nerea' deleted from 'Books'"), findsOne);

      // Verify friend is removed from the list
      expect(find.text("Nerea"), findsNothing);
      expect(find.text("Alex"), findsOne); // Remaining friends
      expect(find.text("Dani"), findsOne);
    });

    testWidgets('delete an expense', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(const ValueKey("expense-2"));

      await tester.drag(expenseRow, const Offset(-500, 0));
      await tester.pumpAndSettle();

      expect(
        find.text("Are you sure you want to delete this expense?"),
        findsOne,
      );

      final deleteButton = find.text("Delete");
      await tester.tap(deleteButton);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Expense 'Coffee' deleted"), findsOne);

      // Verify expense is removed from the list
      expect(expenseRow, findsNothing);
      expect(find.text("Books"), findsOne); // Remaining expenses
      expect(find.text("Dinner"), findsOne);
      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(5));
    });

    testWidgets('add credit to friend in expense', (tester) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Tap on the expense row
      final expenseRow = find.byKey(ValueKey("expense-5")); // For example "Books"
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);

      await tester.pumpAndSettle();

      expect(find.textContaining("\$ 3.30"), findsOne);

      // Find the friend to add credit
      final friendCard = find.byKey(ValueKey("friend-1")); // For example "Nerea"

      // Swipe right to reveal "add credit" option
      await tester.drag(friendCard, const Offset(500, 0));
      await tester.pumpAndSettle();

      // Verify the add credit dialog appears
      expect(find.text("Add Credit"), findsOne);


      // Enter the amount
      final creditField = find.byType(TextField).first;
      await tester.enterText(creditField, "5.50");

      await tester.pump();
      await tester.pump(const Duration(milliseconds: 100));

      final addButton = find.widgetWithText(TextButton, "Add");

      await tester.tap(addButton);
      await tester.pumpAndSettle();

      // Verify snackBar
      expect(find.text("Added \$ 5.50 credit to 'Nerea' in 'Books'"), findsOne);

      // Verify credit is updated in the list
      expect(find.textContaining("\$ 8.80"), findsOne);
      expect(find.textContaining("Credit: \$ 5.50"), findsOne);
    });

    testWidgets('delete friend from expense with error', (
        tester,
        ) async {
      // Load app widget.
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Click on expense
      final expenseRow = find.byKey(ValueKey("expense-5"));
      final inkWellExpense = find.descendant(
          of: expenseRow, matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      final friendCard = find.byKey(ValueKey("friend-4"));
      await tester.drag(friendCard, const Offset(-500, 0)); // Slide to left
      await tester.pumpAndSettle();
      //await tester.pump(const Duration(seconds: 5));
      expect(find.text("Are you sure you want to delete Alex from this expense?"), findsOne);
      final deleteButton = find.text("Delete");
      await tester.tap(deleteButton);
      await tester.pumpAndSettle();

      // Verify snackBar
      final errorMessageFinder = find.text("Cannot delete 'Alex' from Books");
      expect(errorMessageFinder, findsOne);

      final errorSnackBarFinder = find.ancestor(
          of: errorMessageFinder,
          matching: find.byType(Material)
      );
      expect(errorSnackBarFinder, findsOneWidget);

      final dismissButton = find.text("DISMISS");
      expect(dismissButton, findsOneWidget);
      await tester.tap(dismissButton);
      await tester.pumpAndSettle();

      expect(errorSnackBarFinder, findsNothing); // Verify SnackBar is gone

      // Verify all friends still in the list
      expect(find.text("Nerea"), findsOne);
      expect(find.text("Alex"), findsOne);
      expect(find.text("Dani"), findsOne);
    });

    testWidgets('search expenses', (tester) async {
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));

      final searchField = find.byType(TextField).first;
      expect(searchField, findsOneWidget);

      await tester.enterText(searchField, "Coffee");
      await tester.pumpAndSettle();

      expect(find.text("Coffee"), findsNWidgets(2));
      expect(find.text("Groceries"), findsNothing);
      expect(find.text("Dinner"), findsNothing);

      await tester.enterText(searchField, "");
      await tester.pumpAndSettle();

      expect(find.byIcon(FontAwesomeIcons.creditCard), findsNWidgets(6));
    });

    testWidgets('search friends when adding to an expense', (tester) async {
      // Load app widget with mock repositories
      await tester.pumpWidget(MyApp(
        expenseRepository: ExpenseRepository(service: mockService),
        friendRepository: FriendRepository(service: mockService),
      ));

      await tester.pumpAndSettle();

      // Tap on a specific expense (e.g., "Coffee")
      final expenseRow = find.byKey(ValueKey("expense-2"));
      final inkWellExpense = find.descendant(
          of: expenseRow,
          matching: find.byType(InkWell)
      ).first;
      await tester.tap(inkWellExpense);
      await tester.pumpAndSettle();

      // Tap on the "Add friend" button
      final addFriendFab = find.byTooltip("Add friend");
      await tester.tap(addFriendFab);
      await tester.pumpAndSettle();

      // Verify all friends are visible initially
      expect(find.byType(CircleAvatar), findsExactly(6));

      // Find the search TextField inside the "Add friend" overlay/dialog
      final searchField = find.byType(TextField).first;
      expect(searchField, findsOneWidget);

      // Enter a search query to filter friends (e.g., "Pepe")
      await tester.enterText(searchField, "Pepe");
      await tester.pumpAndSettle();

      // Verify only the searched friend is visible
      expect(find.byType(CircleAvatar), findsExactly(1));
      expect(find.text("Pepe"), findsNWidgets(2));


      // Clear the search field
      await tester.enterText(searchField, "");

      await tester.pumpAndSettle(Duration(milliseconds: 100));

      // Verify all friends are visible again
      expect(find.byType(CircleAvatar), findsExactly(6));
    });
  });
}